import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"; // Link bileşenini import et
import { AuthProvider } from "../context/AuthContext"; // AuthProvider'ı import et

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider> {/* AuthProvider ile sarmala */}
          <nav className="bg-gray-800 p-4 text-white">
            <ul className="flex space-x-4">
              <li>
                <Link href="/">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/drops">
                  Drops
                </Link>
              </li>
              <li>
                <Link href="/admin/drops">
                  Admin (Drops)
                </Link>
              </li>
              <li>
                <Link href="/auth/login">
                  Login
                </Link>
              </li>
              <li>
                <Link href="/auth/register">
                  Register
                </Link>
              </li>
            </ul>
          </nav>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
